#!/usr/bin/env python3
"""
the-brief/ingest.py — fetch real-market chart data and upsert into Supabase.

Runs daily from GitHub Actions before update.py. update.py no longer
generates chart data — it only reads from Supabase for narrative references.

Sources
-------
- Brent crude (Yahoo Finance BZ=F futures): reliable, free, no key
- DSEX / LNG / T-Bills / Yield curve: no free public API; these remain
  manually updated OR generated by Claude in update.py and written to
  Supabase via this same script. The current version just refreshes Brent;
  other tables can be extended here as data sources become available.

Environment
-----------
SUPABASE_URL              (required) — https://<ref>.supabase.co
SUPABASE_SERVICE_ROLE_KEY (required) — service_role key (NOT anon)

Exit codes
----------
0 — success
1 — required env var missing
2 — fetch failure (network, bad response)
3 — upsert failure (Supabase error)
"""

from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.request
from datetime import datetime, timezone
from typing import Any

# ============================================================================
# Config
# ============================================================================

# Default to the-brief's project ref so a missing SUPABASE_URL env var
# doesn't break the daily cron. Use `or` instead of the dict default
# because GitHub Actions sets env vars to the empty string (not unset)
# when the referenced secret doesn't exist, which bypasses dict defaults.
SUPABASE_URL = (
    os.environ.get("SUPABASE_URL")
    or "https://ssbliukchgibjcjohibi.supabase.co"
).rstrip("/")
SUPABASE_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY") or ""

YAHOO_BRENT_URL = (
    "https://query1.finance.yahoo.com/v7/finance/chart/BZ=F"
    "?interval=1d&range=1mo"
)
USER_AGENT = "the-brief-ingest/1.0 (+https://thebrief.clauding-lab.com)"


# ============================================================================
# HTTP helpers
# ============================================================================

def http_get_json(url: str, timeout: int = 15) -> dict[str, Any]:
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.loads(resp.read().decode("utf-8"))


def supabase_upsert(table: str, rows: list[dict[str, Any]], on_conflict: str) -> None:
    """POST an array of rows to PostgREST; uses upsert via Prefer header."""
    if not rows:
        print(f"[{table}] nothing to upsert")
        return
    url = f"{SUPABASE_URL}/rest/v1/{table}?on_conflict={on_conflict}"
    data = json.dumps(rows).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=data,
        method="POST",
        headers={
            "apikey": SUPABASE_KEY,
            "Authorization": f"Bearer {SUPABASE_KEY}",
            "Content-Type": "application/json",
            "Prefer": "resolution=merge-duplicates,return=minimal",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=20) as resp:
            if resp.status not in (200, 201, 204):
                raise RuntimeError(f"Upsert {table} returned HTTP {resp.status}")
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"Upsert {table} HTTP {e.code}: {body}") from e


# ============================================================================
# Ingesters
# ============================================================================

def ingest_brent() -> int:
    """Fetch Brent crude futures (BZ=F) from Yahoo Finance, upsert to Supabase.

    Returns the number of rows upserted.
    """
    print(f"[brent] fetching {YAHOO_BRENT_URL}")
    try:
        payload = http_get_json(YAHOO_BRENT_URL)
    except Exception as e:
        print(f"[brent] fetch failed: {e}", file=sys.stderr)
        return 0

    result = payload.get("chart", {}).get("result") or []
    if not result:
        print("[brent] empty result from Yahoo", file=sys.stderr)
        return 0

    chart = result[0]
    timestamps = chart.get("timestamp") or []
    closes = (
        chart.get("indicators", {}).get("quote", [{}])[0].get("close") or []
    )
    meta_symbol = chart.get("meta", {}).get("symbol", "BZ=F")

    rows: list[dict[str, Any]] = []
    for ts, close in zip(timestamps, closes):
        if close is None:
            continue
        iso_date = datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%Y-%m-%d")
        rows.append({
            "date": iso_date,
            "price_usd": round(float(close), 2),
            "source": f"yahoo-{meta_symbol}",
        })

    if not rows:
        print("[brent] no valid rows to upsert", file=sys.stderr)
        return 0

    print(f"[brent] upserting {len(rows)} rows "
          f"({rows[0]['date']} → {rows[-1]['date']})")
    supabase_upsert("tb_brent_daily", rows, on_conflict="date")
    return len(rows)


# ============================================================================
# Main
# ============================================================================

def main() -> int:
    if not SUPABASE_KEY:
        print(
            "ERROR: SUPABASE_SERVICE_ROLE_KEY must be set",
            file=sys.stderr,
        )
        return 1
    print(f"Supabase target: {SUPABASE_URL}")

    print(f"=== the-brief ingest at {datetime.now(timezone.utc).isoformat()} ===")

    totals = {}
    try:
        totals["brent"] = ingest_brent()
    except Exception as e:
        print(f"[brent] upsert failed: {e}", file=sys.stderr)
        return 3

    # Future ingesters go here — DSEX, LNG, USD/BDT, etc. Each writes to its
    # own tb_* table. Keep each ingester isolated so one failure doesn't
    # block the others.

    print("=== ingest complete ===")
    print(json.dumps({"rows_upserted": totals, "timestamp_utc": datetime.now(timezone.utc).isoformat()}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
